[package]
name = "combo"
version = "0.1.8"
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
combo-cli = { path = "../crates/combo-cli" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "combo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
